<?php

namespace App\Services;

use Carbon\Carbon;
use Throwable;

class DecisionSupportService
{
    protected PredictionService $predictionService;

    public function __construct(PredictionService $predictionService)
    {
        $this->predictionService = $predictionService;
    }

    /**
     * Get complete structured data for AI Decision Support Center (`/decision-support`).
     *
     * @param array $simulatedDeltas Optional deltas for Scenario Simulator (weather_delta, inflation_delta, currency_delta, news_delta, delay_delta, prediction_delta)
     * @return array Complete DSS data structure
     */
    public function getDecisionSupportData(array $simulatedDeltas = []): array
    {
        // 1. Fetch baseline and predicted countries data via PredictionService without code duplication
        // Extract basic prediction deltas and pass to PredictionService
        $predDeltas = [
            'weather_delta' => (float) ($simulatedDeltas['weather_delta'] ?? 0),
            'inflation_delta' => (float) ($simulatedDeltas['inflation_delta'] ?? 0),
            'currency_delta' => (float) ($simulatedDeltas['currency_delta'] ?? 0),
            'news_delta' => (float) ($simulatedDeltas['news_delta'] ?? 0),
        ];
        $predictionData = $this->predictionService->getPredictionData($predDeltas);
        $countries = $predictionData['ranking_table'] ?? [];
        
        // Re-enrich country details from prediction service collection for full indicator access
        $detailedCountries = $this->predictionService->collectCountriesData($predDeltas);

        // Apply extra delay and prediction simulation deltas if present
        $delayDelta = (float) ($simulatedDeltas['delay_delta'] ?? 0);
        $predictionDelta = (float) ($simulatedDeltas['prediction_delta'] ?? 0);
        if ($delayDelta != 0 || $predictionDelta != 0) {
            foreach ($detailedCountries as &$c) {
                $c['future_7d_risk'] = $this->clamp($c['future_7d_risk'] + $predictionDelta);
                $c['delay_probability_score'] = $this->clamp($c['delay_probability_score'] + $delayDelta);
                $c['shipping_delay'] = $this->predictionService->classifyShippingDelay($c['delay_probability_score']);
            }
        }

        // 2. Evaluate 40+ Expert Rules & generate Recommended Actions
        $ruleEvaluation = $this->evaluateExpertRules($detailedCountries, $simulatedDeltas);
        $recommendedActions = $ruleEvaluation['actions'];
        $triggeredRuleIds = $ruleEvaluation['triggered_ids'];

        // 3. Financial Impact Analysis (Rule-based financial exposure model)
        $financialModel = $this->calculateFinancialImpact($detailedCountries, $triggeredRuleIds);

        // 4. Decision Score & Emergency Dashboard Level
        $decisionScore = $this->calculateDecisionScore($detailedCountries, $financialModel['total_exposure']);
        $emergencyLevel = $this->classifyEmergencyLevel($decisionScore, $detailedCountries);

        // 5. Decision Matrix (Risk vs Business Impact across 4 Quadrants)
        $decisionMatrix = $this->generateDecisionMatrix($detailedCountries);

        // 6. Alternative Route & Port Recommendations
        $altRoutes = $this->generateAlternativeRoutes($detailedCountries);

        // 7. Alternative Supplier Recommendations
        $altSuppliers = $this->generateAlternativeSuppliers($detailedCountries);

        // 8. Executive Action Timeline (Immediate to Next Week structured by Department)
        $actionTimeline = $this->generateActionTimeline($recommendedActions, $detailedCountries);

        // 9. Strategy Comparison (Current Strategy vs Recommended Rule-Based Strategy)
        $strategyComparison = $this->generateStrategyComparison($detailedCountries, $decisionScore, $financialModel);

        // 10. Executive Summary Narrative (Generated by PHP Rule Engine)
        $executiveSummary = $this->generateExecutiveSummary($detailedCountries, $emergencyLevel, $recommendedActions, $altRoutes);

        // 11. Chart Datasets (Matrix, Financials, Radar, Doughnut Gauge, Exposure Bar)
        $charts = $this->generateChartDatasets($decisionMatrix, $financialModel, $strategyComparison, $decisionScore);

        return [
            'header' => [
                'title' => 'AI Decision Support Center',
                'subtitle' => 'Enterprise Supply Chain Decision System',
                'timestamp' => Carbon::now()->setTimezone('Asia/Jakarta')->format('d M Y, h:i:s A'),
                'status' => 'ONLINE (PHP Rule Engine v2.4 Active)'
            ],
            'kpi_cards' => [
                'decision_score' => $decisionScore,
                'decision_score_badge' => $this->getDecisionScoreBadge($decisionScore),
                'emergency_level' => $emergencyLevel['level'],
                'emergency_color' => $emergencyLevel['color'],
                'business_impact' => round($this->calculateAverage($decisionMatrix, 'impact_score'), 1) . '%',
                'financial_exposure' => '$' . number_format($financialModel['total_exposure'] / 1000, 1) . 'M',
                'estimated_delay' => $this->getHighestDelayDays($detailedCountries),
                'recommended_action' => $recommendedActions[0]['action'] ?? 'Maintain Standard Protocol',
                'supply_chain_stability' => round(100 - $this->calculateAverage($detailedCountries, 'future_7d_risk'), 1) . '%',
                'operational_status' => $emergencyLevel['operational_status']
            ],
            'decision_matrix' => $decisionMatrix,
            'recommended_actions' => $recommendedActions,
            'financial_impact' => $financialModel,
            'alternative_routes' => $altRoutes,
            'alternative_suppliers' => $altSuppliers,
            'action_timeline' => $actionTimeline,
            'emergency_dashboard' => $emergencyLevel,
            'strategy_comparison' => $strategyComparison,
            'executive_summary' => $executiveSummary,
            'charts' => $charts,
            'comparison_engine' => $this->generateComparisonEngineData($detailedCountries),
            'rules_catalog_count' => count($this->getExpertRulesCatalog()),
            'rules_triggered_count' => count($triggeredRuleIds),
            'simulation_applied' => !empty($simulatedDeltas) && (
                ($simulatedDeltas['weather_delta'] ?? 0) != 0 ||
                ($simulatedDeltas['inflation_delta'] ?? 0) != 0 ||
                ($simulatedDeltas['currency_delta'] ?? 0) != 0 ||
                ($simulatedDeltas['news_delta'] ?? 0) != 0 ||
                ($simulatedDeltas['delay_delta'] ?? 0) != 0 ||
                ($simulatedDeltas['prediction_delta'] ?? 0) != 0
            )
        ];
    }

    /**
     * Catalog of at least 40+ structured Expert Rules evaluated by the PHP Rule Engine.
     */
    public function getExpertRulesCatalog(): array
    {
        return [
            // Category 1: Critical Maritime & Congestion Rules (1 - 10)
            ['id' => 'RULE-001', 'category' => 'Maritime Risk', 'condition' => 'Future Risk > 80 AND Delay Score > 70', 'action' => 'Delay Shipment & Execute Emergency Reroute', 'priority' => 'CRITICAL', 'benefit' => 'Prevents total cargo seizure and reduces demurrage fees by 85%.'],
            ['id' => 'RULE-002', 'category' => 'Maritime Risk', 'condition' => 'Port Risk > 65 AND Weather Risk > 60', 'action' => 'Use Alternative Port & Switch Logistics Carrier', 'priority' => 'CRITICAL', 'benefit' => 'Avoids severe storm lockdown saving 5-7 transit days.'],
            ['id' => 'RULE-003', 'category' => 'Maritime Risk', 'condition' => 'Delay Score > 60 AND Future Risk <= 80', 'action' => 'Increase Insurance Coverage (+25% Marine Cargo)', 'priority' => 'HIGH', 'benefit' => 'Protects enterprise profit against container congestion penalties.'],
            ['id' => 'RULE-004', 'category' => 'Maritime Risk', 'condition' => 'Port Risk > 55 AND News Risk > 50', 'action' => 'Contact Logistics Partner & Prioritize Berth Reservation', 'priority' => 'HIGH', 'benefit' => 'Secures priority docking allocation before queue overflow.'],
            ['id' => 'RULE-005', 'category' => 'Maritime Risk', 'condition' => 'Delay Score >= 45 AND Delay Score <= 60', 'action' => 'Increase Safety Stock Buffer by 15%', 'priority' => 'MEDIUM', 'benefit' => 'Mitigates regional stockout risk during mid-level port delays.'],
            ['id' => 'RULE-006', 'category' => 'Maritime Risk', 'condition' => 'Weather Risk > 70 AND Port Risk <= 50', 'action' => 'Hold Vessel Departure for 48 Hours', 'priority' => 'HIGH', 'benefit' => 'Prevents oceanic cargo damage caused by extreme typhoon paths.'],
            ['id' => 'RULE-007', 'category' => 'Maritime Risk', 'condition' => 'Future Risk > 65 AND ISO == CN', 'action' => 'Redirect East Asia Shipments via Singapore Hub', 'priority' => 'CRITICAL', 'benefit' => 'Bypasses South China Sea congestion saving estimated $240,000.'],
            ['id' => 'RULE-008', 'category' => 'Maritime Risk', 'condition' => 'Port Risk > 60 AND ISO == JP', 'action' => 'Expedite Air Freight Backup for High-Value Components', 'priority' => 'HIGH', 'benefit' => 'Maintains automotive assembly line continuity in Tokyo.'],
            ['id' => 'RULE-009', 'category' => 'Maritime Risk', 'condition' => 'Weather Risk > 50 AND Weather Risk <= 70', 'action' => 'Activate Daily Meteorological Route Tracking', 'priority' => 'MEDIUM', 'benefit' => 'Provides early warning course correction for active vessels.'],
            ['id' => 'RULE-010', 'category' => 'Maritime Risk', 'condition' => 'Delay Score < 35 AND Future Risk < 40', 'action' => 'Ship Immediately & Optimize Container Load', 'priority' => 'LOW', 'benefit' => 'Capitalizes on open shipping corridors and low freight rates.'],

            // Category 2: Currency & Inflation Shocks (11 - 20)
            ['id' => 'RULE-011', 'category' => 'Financial Shock', 'condition' => 'Currency Risk > 40 OR Inflation Risk > 45', 'action' => 'Monitor Currency Every 6 Hours & Execute Forward Hedge', 'priority' => 'HIGH', 'benefit' => 'Locks exchange rates to prevent sudden margin erosion.'],
            ['id' => 'RULE-012', 'category' => 'Financial Shock', 'condition' => 'Inflation Risk > 48 AND ISO == IN', 'action' => 'Pre-purchase Raw Materials for 90-Day Supply', 'priority' => 'HIGH', 'benefit' => 'Hedging against hyper-inflationary supplier price adjustments.'],
            ['id' => 'RULE-013', 'category' => 'Financial Shock', 'condition' => 'Currency Risk > 35 AND ISO == JP', 'action' => 'Re-negotiate JPY Settlement Contracts to USD', 'priority' => 'MEDIUM', 'benefit' => 'Neutralizes yen volatility impact on electronics procurement.'],
            ['id' => 'RULE-014', 'category' => 'Financial Shock', 'condition' => 'Inflation Risk > 40 AND ISO == DE', 'action' => 'Adjust European Pricing Buffer by +3.5%', 'priority' => 'MEDIUM', 'benefit' => 'Preserves gross margin amidst rising energy and freight surcharges.'],
            ['id' => 'RULE-015', 'category' => 'Financial Shock', 'condition' => 'Currency Risk > 30 AND Currency Risk <= 40', 'action' => 'Maintain Dual-Currency Treasury Reserve', 'priority' => 'MEDIUM', 'benefit' => 'Ensures liquidity flexibility across major settlement hubs.'],
            ['id' => 'RULE-016', 'category' => 'Financial Shock', 'condition' => 'Inflation Risk > 35 AND Port Risk > 45', 'action' => 'Consolidate LCL Cargo to FCL Containers', 'priority' => 'MEDIUM', 'benefit' => 'Reduces unit handling fees by 18% during inflationary peaks.'],
            ['id' => 'RULE-017', 'category' => 'Financial Shock', 'condition' => 'Currency Risk < 20 AND Inflation Risk < 25', 'action' => 'Extend Long-Term Fixed Price Supplier Agreements', 'priority' => 'LOW', 'benefit' => 'Secures favorable multi-year cost structures.'],
            ['id' => 'RULE-018', 'category' => 'Financial Shock', 'condition' => 'Currency Risk > 45 AND News Risk > 40', 'action' => 'Freeze Non-Essential Capital Outflows in Corridor', 'priority' => 'CRITICAL', 'benefit' => 'Protects corporate working capital from sudden currency devaluation.'],
            ['id' => 'RULE-019', 'category' => 'Financial Shock', 'condition' => 'Inflation Risk > 38 AND ISO == GB', 'action' => 'Review UK Warehousing Lease Terms & Tariff Buffers', 'priority' => 'MEDIUM', 'benefit' => 'Mitigates post-customs storage inflation surges.'],
            ['id' => 'RULE-020', 'category' => 'Financial Shock', 'condition' => 'Currency Risk > 25 AND Delay Score > 50', 'action' => 'Require Letter of Credit (L/C) for All Transit Shipments', 'priority' => 'HIGH', 'benefit' => 'Eliminates counterparty default risk during extended transit.'],

            // Category 3: Geopolitics & News Sentiment (21 - 30)
            ['id' => 'RULE-021', 'category' => 'Geopolitical Intelligence', 'condition' => 'News Risk > 60 AND Future Risk > 55', 'action' => 'Activate Tier-1 Geopolitical Emergency Protocol', 'priority' => 'CRITICAL', 'benefit' => 'Immediate supply redirection preventing trade embargo disruption.'],
            ['id' => 'RULE-022', 'category' => 'Geopolitical Intelligence', 'condition' => 'News Risk > 50 AND ISO == CN', 'action' => 'Diversify 40% Manufacturing Order to Southeast Asia', 'priority' => 'HIGH', 'benefit' => 'De-risks single-country dependency across trade restriction zones.'],
            ['id' => 'RULE-023', 'category' => 'Geopolitical Intelligence', 'condition' => 'News Risk > 45 AND Port Risk > 45', 'action' => 'Increase Customs Clearance Buffer by 4 Business Days', 'priority' => 'MEDIUM', 'benefit' => 'Prevents regulatory inspection delays from disrupting delivery schedules.'],
            ['id' => 'RULE-024', 'category' => 'Geopolitical Intelligence', 'condition' => 'News Risk > 40 AND ISO == US', 'action' => 'Audit Bilateral Trade Compliance & Tariff Classifications', 'priority' => 'MEDIUM', 'benefit' => 'Ensures 100% adherence to evolving North American import regulations.'],
            ['id' => 'RULE-025', 'category' => 'Geopolitical Intelligence', 'condition' => 'News Risk > 35 AND Currency Risk > 35', 'action' => 'Conduct Daily Supplier Viability Stress Test', 'priority' => 'MEDIUM', 'benefit' => 'Identifies financial distress in key tier-2 vendors early.'],
            ['id' => 'RULE-026', 'category' => 'Geopolitical Intelligence', 'condition' => 'News Risk <= 30 AND Future Risk <= 45', 'action' => 'Maintain Standard Geopolitical Watchlist Frequency', 'priority' => 'LOW', 'benefit' => 'Optimizes analyst resources for stable trade regions.'],
            ['id' => 'RULE-027', 'category' => 'Geopolitical Intelligence', 'condition' => 'News Risk > 55 AND Weather Risk > 55', 'action' => 'Deploy Cross-Functional Crisis Taskforce', 'priority' => 'CRITICAL', 'benefit' => 'Provides unified executive response to compounded environmental-political shocks.'],
            ['id' => 'RULE-028', 'category' => 'Geopolitical Intelligence', 'condition' => 'News Risk > 42 AND ISO == IN', 'action' => 'Pre-clear Export Documentation via Digital Portals', 'priority' => 'MEDIUM', 'benefit' => 'Reduces port gate documentation dwell time by 60%.'],
            ['id' => 'RULE-029', 'category' => 'Geopolitical Intelligence', 'condition' => 'News Risk > 38 AND ISO == DE', 'action' => 'Assess European Rail Transit Backup Alternatives', 'priority' => 'MEDIUM', 'benefit' => 'Provides multimodal contingency against overland border bottlenecks.'],
            ['id' => 'RULE-030', 'category' => 'Geopolitical Intelligence', 'condition' => 'News Risk > 50 AND Delay Score > 50', 'action' => 'Notify Executive Committee of Potential SLA Breach', 'priority' => 'HIGH', 'benefit' => 'Ensures proactive stakeholder communication before customer impact.'],

            // Category 4: Supplier Reliability & Inventory Strategy (31 - 42)
            ['id' => 'RULE-031', 'category' => 'Supplier Strategy', 'condition' => 'Future Risk > 60 AND Supplier Reliability < 85%', 'action' => 'Use Backup Supplier & Split Purchase Order 50/50', 'priority' => 'HIGH', 'benefit' => 'Guarantees component flow even if primary facility experiences downtime.'],
            ['id' => 'RULE-032', 'category' => 'Supplier Strategy', 'condition' => 'Delay Score > 55 AND Inventory Buffer < 20 Days', 'action' => 'Increase Inventory & Air-Freight Emergency Buffer', 'priority' => 'HIGH', 'benefit' => 'Secures safety stock before ocean shipping cutoff dates.'],
            ['id' => 'RULE-033', 'category' => 'Supplier Strategy', 'condition' => 'Current Risk > 55 AND ISO == ID', 'action' => 'Audit Tanjung Priok Port Terminal Congestion Rates', 'priority' => 'MEDIUM', 'benefit' => 'Avoids local domestic transshipment bottlenecks.'],
            ['id' => 'RULE-034', 'category' => 'Supplier Strategy', 'condition' => 'Future Risk < 35 AND Delay Score < 35', 'action' => 'Implement Just-In-Time (JIT) Inventory Replenishment', 'priority' => 'LOW', 'benefit' => 'Reduces working capital tied up in warehouse safety stocks.'],
            ['id' => 'RULE-035', 'category' => 'Supplier Strategy', 'condition' => 'Inflation Risk > 40 AND Supplier Reliability > 90%', 'action' => 'Lock 6-Month Volume Commitment for Volume Discount', 'priority' => 'MEDIUM', 'benefit' => 'Offsets inflationary unit price increases via economies of scale.'],
            ['id' => 'RULE-036', 'category' => 'Supplier Strategy', 'condition' => 'Weather Risk > 60 AND ISO == JP', 'action' => 'Relocate Sensitive Semiconductor Inventory Inland', 'priority' => 'HIGH', 'benefit' => 'Protects critical precision inventory from coastal typhoon flooding.'],
            ['id' => 'RULE-037', 'category' => 'Supplier Strategy', 'condition' => 'Port Risk > 50 AND ISO == SG', 'action' => 'Utilize Jurong Port Secondary Berths for Bulk Transshipment', 'priority' => 'MEDIUM', 'benefit' => 'Maintains Singapore transshipment speed during peak terminal hours.'],
            ['id' => 'RULE-038', 'category' => 'Supplier Strategy', 'condition' => 'News Risk > 45 AND ISO == AU', 'action' => 'Verify Mineral & Agricultural Export Quota Allocations', 'priority' => 'MEDIUM', 'benefit' => 'Ensures uninterrupted bulk commodity supply chains.'],
            ['id' => 'RULE-039', 'category' => 'Supplier Strategy', 'condition' => 'Currency Risk > 35 AND ISO == NL', 'action' => 'Establish Euro Rotational Hub Storage Account', 'priority' => 'MEDIUM', 'benefit' => 'Minimizes cross-border European customs handling costs.'],
            ['id' => 'RULE-040', 'category' => 'Supplier Strategy', 'condition' => 'Future Risk > 70 AND Total Exposure > $2,000,000', 'action' => 'Convene Board-Level Risk Mitigation Conference', 'priority' => 'CRITICAL', 'benefit' => 'Authorizes emergency capital allocation for enterprise continuity.'],
            ['id' => 'RULE-041', 'category' => 'Supplier Strategy', 'condition' => 'Delay Score > 65 AND Port Risk > 60', 'action' => 'Reroute Cargo via Panama/Suez Alternative Canals', 'priority' => 'CRITICAL', 'benefit' => 'Circumnavigates primary maritime choke points.'],
            ['id' => 'RULE-042', 'category' => 'Supplier Strategy', 'condition' => 'Global Risk Average > 48 AND Confidence > 90%', 'action' => 'Execute Automated Multi-Corridor Hedging Protocol', 'priority' => 'HIGH', 'benefit' => 'Dynamically balances risk exposure across all 10 monitored nations.']
        ];
    }

    /**
     * Evaluate detailed countries against the 40+ expert rules to generate prioritized recommendations.
     */
    public function evaluateExpertRules(array $countries, array $simulatedDeltas = []): array
    {
        $catalog = $this->getExpertRulesCatalog();
        $triggeredActions = [];
        $triggeredIds = [];

        $globalRiskAvg = $this->calculateAverage($countries, 'future_7d_risk');
        $globalDelayAvg = $this->calculateAverage($countries, 'delay_probability_score');
        $globalCurrencyAvg = $this->calculateAverage($countries, 'currency_risk');
        $globalInflationAvg = $this->calculateAverage($countries, 'inflation_risk');
        $globalNewsAvg = $this->calculateAverage($countries, 'news_risk');

        foreach ($countries as $c) {
            $fRisk = (float) $c['future_7d_risk'];
            $cRisk = (float) $c['current_risk'];
            $wRisk = (float) $c['weather_risk'];
            $iRisk = (float) $c['inflation_risk'];
            $curRisk = (float) $c['currency_risk'];
            $nRisk = (float) $c['news_risk'];
            $pRisk = (float) $c['port_risk'];
            $dScore = (float) $c['delay_probability_score'];
            $iso = $c['iso'];

            foreach ($catalog as $rule) {
                // Rule evaluation engine logic
                $isMatch = false;

                switch ($rule['id']) {
                    case 'RULE-001':
                        if ($fRisk > 80 || ($fRisk > 65 && $dScore > 65)) $isMatch = true;
                        break;
                    case 'RULE-002':
                        if ($pRisk > 60 && $wRisk > 55) $isMatch = true;
                        break;
                    case 'RULE-003':
                        if ($dScore > 50 && $fRisk <= 80) $isMatch = true;
                        break;
                    case 'RULE-004':
                        if ($pRisk > 50 && $nRisk > 45) $isMatch = true;
                        break;
                    case 'RULE-005':
                        if ($dScore >= 40 && $dScore <= 60) $isMatch = true;
                        break;
                    case 'RULE-006':
                        if ($wRisk > 60 && $pRisk <= 60) $isMatch = true;
                        break;
                    case 'RULE-007':
                        if ($fRisk > 58 && $iso === 'CN') $isMatch = true;
                        break;
                    case 'RULE-008':
                        if ($pRisk > 52 && $iso === 'JP') $isMatch = true;
                        break;
                    case 'RULE-009':
                        if ($wRisk > 45 && $wRisk <= 65) $isMatch = true;
                        break;
                    case 'RULE-010':
                        if ($dScore < 35 && $fRisk < 40) $isMatch = true;
                        break;
                    case 'RULE-011':
                        if ($curRisk > 35 || $iRisk > 40 || $globalCurrencyAvg > 30) $isMatch = true;
                        break;
                    case 'RULE-012':
                        if ($iRisk > 45 && $iso === 'IN') $isMatch = true;
                        break;
                    case 'RULE-013':
                        if ($curRisk > 35 && $iso === 'JP') $isMatch = true;
                        break;
                    case 'RULE-014':
                        if ($iRisk > 38 && $iso === 'DE') $isMatch = true;
                        break;
                    case 'RULE-015':
                        if ($curRisk > 25 && $curRisk <= 40) $isMatch = true;
                        break;
                    case 'RULE-016':
                        if ($iRisk > 32 && $pRisk > 40) $isMatch = true;
                        break;
                    case 'RULE-017':
                        if ($curRisk < 22 && $iRisk < 28) $isMatch = true;
                        break;
                    case 'RULE-018':
                        if ($curRisk > 40 && $nRisk > 35) $isMatch = true;
                        break;
                    case 'RULE-019':
                        if ($iRisk > 38 && $iso === 'GB') $isMatch = true;
                        break;
                    case 'RULE-020':
                        if ($curRisk > 25 && $dScore > 48) $isMatch = true;
                        break;
                    case 'RULE-021':
                        if ($nRisk > 58 && $fRisk > 52) $isMatch = true;
                        break;
                    case 'RULE-022':
                        if ($nRisk > 48 && $iso === 'CN') $isMatch = true;
                        break;
                    case 'RULE-023':
                        if ($nRisk > 42 && $pRisk > 42) $isMatch = true;
                        break;
                    case 'RULE-024':
                        if ($nRisk > 38 && $iso === 'US') $isMatch = true;
                        break;
                    case 'RULE-025':
                        if ($nRisk > 35 && $curRisk > 32) $isMatch = true;
                        break;
                    case 'RULE-026':
                        if ($nRisk <= 32 && $fRisk <= 45) $isMatch = true;
                        break;
                    case 'RULE-027':
                        if ($nRisk > 50 && $wRisk > 52) $isMatch = true;
                        break;
                    case 'RULE-028':
                        if ($nRisk > 40 && $iso === 'IN') $isMatch = true;
                        break;
                    case 'RULE-029':
                        if ($nRisk > 35 && $iso === 'DE') $isMatch = true;
                        break;
                    case 'RULE-030':
                        if ($nRisk > 48 && $dScore > 48) $isMatch = true;
                        break;
                    case 'RULE-031':
                        if ($fRisk > 55) $isMatch = true;
                        break;
                    case 'RULE-032':
                        if ($dScore > 50) $isMatch = true;
                        break;
                    case 'RULE-033':
                        if ($cRisk > 42 && $iso === 'ID') $isMatch = true;
                        break;
                    case 'RULE-034':
                        if ($fRisk < 35 && $dScore < 35) $isMatch = true;
                        break;
                    case 'RULE-035':
                        if ($iRisk > 35) $isMatch = true;
                        break;
                    case 'RULE-036':
                        if ($wRisk > 58 && $iso === 'JP') $isMatch = true;
                        break;
                    case 'RULE-037':
                        if ($pRisk > 45 && $iso === 'SG') $isMatch = true;
                        break;
                    case 'RULE-038':
                        if ($nRisk > 40 && $iso === 'AU') $isMatch = true;
                        break;
                    case 'RULE-039':
                        if ($curRisk > 32 && $iso === 'NL') $isMatch = true;
                        break;
                    case 'RULE-040':
                        if ($fRisk > 62) $isMatch = true;
                        break;
                    case 'RULE-041':
                        if ($dScore > 60 && $pRisk > 55) $isMatch = true;
                        break;
                    case 'RULE-042':
                        if ($globalRiskAvg > 45) $isMatch = true;
                        break;
                }

                if ($isMatch && !in_array($rule['id'] . '-' . $iso, $triggeredIds)) {
                    $triggeredIds[] = $rule['id'] . '-' . $iso;
                    
                    // Format actionable card item
                    $triggeredActions[] = [
                        'rule_id' => $rule['id'],
                        'country' => $c['name'],
                        'iso' => $iso,
                        'category' => $rule['category'],
                        'action' => $rule['action'],
                        'priority' => $rule['priority'],
                        'reason' => "Triggered by corridor {$c['name']}: {$rule['condition']} (Current Risk: {$cRisk}%, Delay: {$dScore}%)",
                        'benefit' => $rule['benefit'],
                        'priority_color' => $this->getPriorityColor($rule['priority'])
                    ];
                }
            }
        }

        // Sort by Priority (CRITICAL -> HIGH -> MEDIUM -> LOW)
        $priorityOrder = ['CRITICAL' => 1, 'HIGH' => 2, 'MEDIUM' => 3, 'LOW' => 4];
        usort($triggeredActions, function ($a, $b) use ($priorityOrder) {
            return ($priorityOrder[$a['priority']] ?? 5) <=> ($priorityOrder[$b['priority']] ?? 5);
        });

        // Take top 12 most critical distinct actions for dashboard display
        return [
            'actions' => array_slice($triggeredActions, 0, 12),
            'triggered_ids' => $triggeredIds
        ];
    }

    /**
     * Calculate Financial Impact (Delay Cost, Insurance, Inventory, Revenue Loss, Total Exposure).
     */
    public function calculateFinancialImpact(array $countries, array $triggeredIds): array
    {
        // Base economic volume assumption per corridor ($500,000 daily transit baseline)
        $delayCost = 0;
        $insuranceCost = 0;
        $inventoryCost = 0;
        $revenueRisk = 0;
        $currencyLoss = 0;

        foreach ($countries as $c) {
            $fRisk = (float) $c['future_7d_risk'];
            $dScore = (float) $c['delay_probability_score'];
            $wRisk = (float) $c['weather_risk'];
            $iRisk = (float) $c['inflation_risk'];
            $curRisk = (float) $c['currency_risk'];
            $pRisk = (float) $c['port_risk'];

            // Estimated delay days
            $days = 1;
            if ($dScore >= 65) $days = 7;
            elseif ($dScore >= 50) $days = 5;
            elseif ($dScore >= 35) $days = 3;

            // Dollar impact formulas
            $delayCost += ($days * 85000) * ($fRisk / 50);
            $insuranceCost += ($wRisk * 1200) + ($pRisk * 1500);
            $inventoryCost += ($iRisk * 2200) + ($days * 18000);
            $revenueRisk += ($dScore * 4500) * ($fRisk > 60 ? 1.8 : 1.0);
            $currencyLoss += ($curRisk * 3800);
        }

        $totalExposure = round($delayCost + $insuranceCost + $inventoryCost + $revenueRisk + $currencyLoss, 2);

        return [
            'delay_cost' => round($delayCost, 2),
            'insurance_cost' => round($insuranceCost, 2),
            'inventory_cost' => round($inventoryCost, 2),
            'revenue_risk' => round($revenueRisk, 2),
            'currency_loss' => round($currencyLoss, 2),
            'total_exposure' => $totalExposure,
            'formatted_total' => '$' . number_format($totalExposure, 2),
            'breakdown_table' => [
                ['component' => 'Shipping Delay Cost (Demurrage & Transit)', 'amount' => round($delayCost, 2), 'pct' => round(($delayCost / max(1, $totalExposure)) * 100, 1), 'icon' => 'fa-ship text-danger'],
                ['component' => 'Marine Insurance Coverage Premiums', 'amount' => round($insuranceCost, 2), 'pct' => round(($insuranceCost / max(1, $totalExposure)) * 100, 1), 'icon' => 'fa-shield-halved text-info'],
                ['component' => 'Safety Stock Inventory Holding Buffer', 'amount' => round($inventoryCost, 2), 'pct' => round(($inventoryCost / max(1, $totalExposure)) * 100, 1), 'icon' => 'fa-boxes-stacked text-warning'],
                ['component' => 'Revenue Risk (Potential Stockout Loss)', 'amount' => round($revenueRisk, 2), 'pct' => round(($revenueRisk / max(1, $totalExposure)) * 100, 1), 'icon' => 'fa-chart-line text-danger'],
                ['component' => 'Currency Exchange Devaluation Exposure', 'amount' => round($currencyLoss, 2), 'pct' => round(($currencyLoss / max(1, $totalExposure)) * 100, 1), 'icon' => 'fa-money-bill-transfer text-success']
            ]
        ];
    }

    /**
     * Calculate composite Decision Score (0 - 100).
     */
    public function calculateDecisionScore(array $countries, float $totalExposure): float
    {
        $avgPrediction = $this->calculateAverage($countries, 'future_7d_risk');
        $avgDelay = $this->calculateAverage($countries, 'delay_probability_score');
        $avgWeather = $this->calculateAverage($countries, 'weather_risk');
        $avgNews = $this->calculateAverage($countries, 'news_risk');
        $avgInflation = $this->calculateAverage($countries, 'inflation_risk');
        $avgCurrency = $this->calculateAverage($countries, 'currency_risk');

        // Financial exposure scaling factor ($5M exposure = 100%)
        $exposureScore = min(100, ($totalExposure / 5000000) * 100);

        // Weighted formula
        $composite = ($avgPrediction * 0.30) +
                     ($avgDelay * 0.25) +
                     ($exposureScore * 0.15) +
                     ($avgWeather * 0.12) +
                     ($avgNews * 0.10) +
                     (($avgInflation + $avgCurrency) * 0.04);

        return round($this->clamp($composite), 1);
    }

    /**
     * Classify Emergency Dashboard Level.
     */
    public function classifyEmergencyLevel(float $decisionScore, array $countries): array
    {
        $maxCountryRisk = 0;
        foreach ($countries as $c) {
            if ($c['future_7d_risk'] > $maxCountryRisk) $maxCountryRisk = $c['future_7d_risk'];
        }

        if ($decisionScore >= 70 || $maxCountryRisk >= 80) {
            return [
                'level' => 'Emergency',
                'color' => 'danger',
                'badge_class' => 'bg-danger text-white border-2 border-light animate-pulse',
                'description' => 'Immediate Board-level intervention required. Execute alternative port rerouting across high-risk corridors.',
                'operational_status' => 'CRITICAL PROTOCOL ACTIVE',
                'score' => $decisionScore
            ];
        } elseif ($decisionScore >= 55 || $maxCountryRisk >= 68) {
            return [
                'level' => 'Critical',
                'color' => 'danger',
                'badge_class' => 'bg-danger text-white',
                'description' => 'Severe maritime congestion and inflation headwinds. Activate secondary logistics carriers and hedge currency.',
                'operational_status' => 'ELEVATED ALERT',
                'score' => $decisionScore
            ];
        } elseif ($decisionScore >= 40) {
            return [
                'level' => 'Warning',
                'color' => 'warning',
                'badge_class' => 'bg-warning text-dark',
                'description' => 'Moderate supply chain volatility detected. Increase safety stock buffers by 15% across affected routes.',
                'operational_status' => 'PRECAUTIONARY WATCH',
                'score' => $decisionScore
            ];
        } elseif ($decisionScore >= 25) {
            return [
                'level' => 'Watch',
                'color' => 'info',
                'badge_class' => 'bg-info text-dark',
                'description' => 'Corridor conditions stable with slight meteorological disturbances. Monitor exchange rates every 6 hours.',
                'operational_status' => 'ACTIVE MONITORING',
                'score' => $decisionScore
            ];
        }

        return [
            'level' => 'Normal',
            'color' => 'success',
            'badge_class' => 'bg-success text-white',
            'description' => 'All global supply chain corridors operating at peak efficiency. Standard Just-In-Time replenishment active.',
            'operational_status' => 'OPTIMAL OPERATIONS',
            'score' => $decisionScore
        ];
    }

    /**
     * Generate interactive Decision Matrix (Risk vs Business Impact across 4 Quadrants).
     */
    public function generateDecisionMatrix(array $countries): array
    {
        $matrix = [];
        foreach ($countries as $c) {
            $risk = (float) $c['future_7d_risk'];
            // Business Impact score combines economic volume (port + inflation + delay)
            $impact = round($this->clamp(($c['port_risk'] * 0.45) + ($c['delay_probability_score'] * 0.35) + ($c['inflation_risk'] * 0.20)), 1);

            $quadrant = 'Low Risk Low Impact';
            $quadrantColor = 'success';
            if ($risk >= 50 && $impact >= 50) {
                $quadrant = 'High Risk High Impact';
                $quadrantColor = 'danger';
            } elseif ($risk >= 50 && $impact < 50) {
                $quadrant = 'High Risk Low Impact';
                $quadrantColor = 'warning';
            } elseif ($risk < 50 && $impact >= 50) {
                $quadrant = 'Low Risk High Impact';
                $quadrantColor = 'info';
            }

            $matrix[] = [
                'country' => $c['name'],
                'iso' => $c['iso'],
                'risk_score' => $risk,
                'impact_score' => $impact,
                'quadrant' => $quadrant,
                'color' => $quadrantColor,
                'delay_days' => $c['shipping_delay']['days'] ?? '1 Day'
            ];
        }

        return $matrix;
    }

    /**
     * Generate Alternative Route & Port Recommendations for impacted corridors.
     */
    public function generateAlternativeRoutes(array $countries): array
    {
        $portMap = [
            'CN' => ['port' => 'Singapore Hub (Jurong/Pasir Panjang)', 'route' => 'Malacca Strait Bypass Express', 'saved_days' => '5 Days', 'risk_red' => '38%', 'reason' => 'Bypasses South China Sea terminal congestion and typhoon paths.'],
            'JP' => ['port' => 'Busan New Port Hub (South Korea)', 'route' => 'Korea Strait High-Speed Ferry Route', 'saved_days' => '3 Days', 'risk_red' => '28%', 'reason' => 'Avoids eastern Pacific weather anomalies and port queue dwell.'],
            'ID' => ['port' => 'Port Klang Transshipment Terminal (Malaysia)', 'route' => 'Strait of Malacca Feeder Shuttle', 'saved_days' => '2 Days', 'risk_red' => '22%', 'reason' => 'Reduces Tanjung Priok customs clearance backlogs.'],
            'IN' => ['port' => 'Colombo Port Hub (Sri Lanka)', 'route' => 'Indian Ocean Express Corridor', 'saved_days' => '4 Days', 'risk_red' => '32%', 'reason' => 'Circumnavigates Mumbai/Nhava Sheva seasonal monsoon bottlenecks.'],
            'US' => ['port' => 'Port of Savannah / Houston Alternative', 'route' => 'Panama Canal Direct East Coast Route', 'saved_days' => '3 Days', 'risk_red' => '25%', 'reason' => 'Mitigates West Coast (Los Angeles/Long Beach) rail yard congestion.'],
            'GB' => ['port' => 'Port of Rotterdam (Netherlands)', 'route' => 'Channel Tunnel Freight Rail Link', 'saved_days' => '2 Days', 'risk_red' => '20%', 'reason' => 'Reduces cross-channel border inspection dwell times.'],
            'DE' => ['port' => 'Port of Antwerp-Bruges (Belgium)', 'route' => 'Rhine Barge Inland Waterway Express', 'saved_days' => '2 Days', 'risk_red' => '18%', 'reason' => 'Provides secondary rail/waterway entry into Central Europe.'],
        ];

        $results = [];
        foreach ($countries as $c) {
            $iso = $c['iso'];
            if ($c['future_7d_risk'] >= 45 || $c['delay_probability_score'] >= 45) {
                if (isset($portMap[$iso])) {
                    $results[] = [
                        'country' => $c['name'],
                        'iso' => $iso,
                        'current_port' => "Primary Hub ({$c['name']})",
                        'alt_port' => $portMap[$iso]['port'],
                        'alt_route' => $portMap[$iso]['route'],
                        'saved_days' => $portMap[$iso]['saved_days'],
                        'risk_reduction' => $portMap[$iso]['risk_red'],
                        'reason' => $portMap[$iso]['reason'],
                        'risk_level' => $c['future_7d_risk'] >= 65 ? 'Critical' : 'High'
                    ];
                }
            }
        }

        // Fallback default if all corridors are super calm
        if (empty($results)) {
            $results[] = [
                'country' => 'China',
                'iso' => 'CN',
                'current_port' => 'Shanghai Port Terminal',
                'alt_port' => 'Singapore Hub (Jurong/Pasir Panjang)',
                'alt_route' => 'Malacca Strait Bypass Express',
                'saved_days' => '5 Days',
                'risk_reduction' => '38%',
                'reason' => 'Precautionary alternative corridor maintained by PHP Rule Engine.',
                'risk_level' => 'Warning'
            ];
        }

        return $results;
    }

    /**
     * Generate Alternative Supplier Recommendations.
     */
    public function generateAlternativeSuppliers(array $countries): array
    {
        $supplierCatalog = [
            'CN' => ['primary' => 'Shenzhen Electronics Consortium', 'backup' => 'Penang Tech Assembly Hub (Malaysia)', 'risk' => 'High', 'score' => '96%', 'reason' => 'De-risks East Asia tariffs and shipping queue bottlenecks.'],
            'JP' => ['primary' => 'Tokyo Precision Micro-Optics', 'backup' => 'Taipei Semiconductor Works (Taiwan)', 'risk' => 'Medium', 'score' => '94%', 'reason' => 'Provides secondary cleanroom manufacturing capacity.'],
            'IN' => ['primary' => 'Mumbai Pharmaceutical Exports', 'backup' => 'Singapore Bio-Chemical Logistics', 'risk' => 'High', 'score' => '98%', 'reason' => 'Ensures active API compound delivery during monsoon seasons.'],
            'DE' => ['primary' => 'Stuttgart Automotive Parts GmbH', 'backup' => 'Eindhoven Advanced Systems (Netherlands)', 'risk' => 'Medium', 'score' => '97%', 'reason' => 'Mitigates German rail freight surcharges and energy spikes.'],
            'US' => ['primary' => 'Texas Petro-Chemical Refinery', 'backup' => 'Calgary Resource Supply Hub (Canada)', 'risk' => 'Low', 'score' => '95%', 'reason' => 'Guarantees cross-border North American industrial supply.'],
            'ID' => ['primary' => 'Jakarta Palm & Agro Commodities', 'backup' => 'Kuala Lumpur Agro Alliance (Malaysia)', 'risk' => 'Medium', 'score' => '93%', 'reason' => 'Diversifies agricultural bulk shipments across both sides of Malacca.']
        ];

        $results = [];
        foreach ($countries as $c) {
            $iso = $c['iso'];
            if (isset($supplierCatalog[$iso])) {
                $results[] = [
                    'country' => $c['name'],
                    'iso' => $iso,
                    'primary_supplier' => $supplierCatalog[$iso]['primary'],
                    'backup_supplier' => $supplierCatalog[$iso]['backup'],
                    'supplier_risk' => $c['future_7d_risk'] >= 60 ? 'High' : ($c['future_7d_risk'] >= 40 ? 'Medium' : 'Low'),
                    'reliability_score' => $supplierCatalog[$iso]['score'],
                    'business_reason' => $supplierCatalog[$iso]['reason']
                ];
            }
        }

        return $results;
    }

    /**
     * Generate Executive Action Timeline across departments.
     */
    public function generateActionTimeline(array $recommendedActions, array $countries): array
    {
        $timeline = [
            'Immediate' => [],
            'Today' => [],
            'Tomorrow' => [],
            'This Week' => [],
            'Next Week' => []
        ];

        foreach ($recommendedActions as $idx => $act) {
            $dept = 'Logistics Operations';
            if (str_contains(strtolower($act['action']), 'insurance') || str_contains(strtolower($act['action']), 'hedge') || str_contains(strtolower($act['action']), 'currency')) {
                $dept = 'Corporate Treasury & Finance';
            } elseif (str_contains(strtolower($act['action']), 'supplier') || str_contains(strtolower($act['action']), 'purchase')) {
                $dept = 'Global Procurement';
            } elseif ($act['priority'] === 'CRITICAL') {
                $dept = 'Executive Risk Committee';
            }

            $item = [
                'action' => $act['action'],
                'priority' => $act['priority'],
                'department' => $dept,
                'country' => $act['country'],
                'reason' => $act['reason'],
                'priority_color' => $act['priority_color']
            ];

            if ($act['priority'] === 'CRITICAL' || $idx < 2) {
                $timeline['Immediate'][] = $item;
            } elseif ($act['priority'] === 'HIGH' || $idx < 5) {
                $timeline['Today'][] = $item;
            } elseif ($idx < 8) {
                $timeline['Tomorrow'][] = $item;
            } elseif ($idx < 10) {
                $timeline['This Week'][] = $item;
            } else {
                $timeline['Next Week'][] = $item;
            }
        }

        // Fill empty buckets with standard oversight tasks if needed
        if (empty($timeline['Immediate'])) {
            $timeline['Immediate'][] = ['action' => 'Execute Daily Maritime Corridor Synchronization', 'priority' => 'HIGH', 'department' => 'Logistics Operations', 'country' => 'Global', 'reason' => 'Standard real-time tracking verification.', 'priority_color' => 'warning'];
        }
        if (empty($timeline['Tomorrow'])) {
            $timeline['Tomorrow'][] = ['action' => 'Review Customs Pre-Clearance Documentation', 'priority' => 'MEDIUM', 'department' => 'Global Procurement', 'country' => 'Global', 'reason' => 'Ensures smooth gate passage.', 'priority_color' => 'info'];
        }

        return $timeline;
    }

    /**
     * Generate Strategy Comparison (Current vs Recommended Strategy).
     */
    public function generateStrategyComparison(array $countries, float $decisionScore, array $financialModel): array
    {
        $currRisk = $this->calculateAverage($countries, 'future_7d_risk');
        $currDelayDays = $this->getHighestDelayDays($countries);
        $currExposure = $financialModel['total_exposure'];

        // Recommended strategy reduces risk by ~38%, delay by ~65%, exposure by ~75%
        $recRisk = round($this->clamp($currRisk * 0.62), 1);
        $recDelayDays = '1 Day (Express Hub)';
        if ($currDelayDays === '7 Days') $recDelayDays = '2 Days (Alternative Port)';
        elseif ($currDelayDays === '5 Days') $recDelayDays = '1 Day (Expedited Hub)';

        $recExposure = round($currExposure * 0.25, 2);

        return [
            'table' => [
                ['metric' => 'Global Supply Chain Risk Score', 'current' => "{$currRisk}%", 'recommended' => "{$recRisk}%", 'improvement' => '-38% Risk Reduction', 'color' => 'success'],
                ['metric' => 'Expected Shipping Delay Duration', 'current' => $currDelayDays, 'recommended' => $recDelayDays, 'improvement' => 'Saved 3-5 Transit Days', 'color' => 'info'],
                ['metric' => 'Total Financial Exposure & Demurrage', 'current' => '$' . number_format($currExposure, 0), 'recommended' => '$' . number_format($recExposure, 0), 'improvement' => '$' . number_format($currExposure - $recExposure, 0) . ' Protected', 'color' => 'warning'],
                ['metric' => 'Gross Profit Margin Preservation', 'current' => '68.5% (Eroded)', 'recommended' => '94.2% (Protected)', 'improvement' => '+25.7% Profit Buffer', 'color' => 'success'],
                ['metric' => 'Operational Congestion Status', 'current' => 'High Terminal Dwell', 'recommended' => 'Optimized Priority Flow', 'improvement' => 'Zero Berth Queue', 'color' => 'info']
            ],
            'chart_data' => [
                'labels' => ['Risk Level (%)', 'Delay Impact (%)', 'Exposure Index (%)', 'Profit Protection (%)', 'Efficiency Score (%)'],
                'current_strategy' => [$currRisk, 75.0, min(100, round(($currExposure / 5000000) * 100, 1)), 68.5, 55.0],
                'recommended_strategy' => [$recRisk, 25.0, min(100, round(($recExposure / 5000000) * 100, 1)), 94.2, 95.0]
            ]
        ];
    }

    /**
     * Generate automated Executive Summary using PHP Rule Engine.
     */
    public function generateExecutiveSummary(array $countries, array $emergencyLevel, array $recommendedActions, array $altRoutes): string
    {
        $topRiskName = $countries[0]['name'] ?? 'China';
        $topRiskScore = $countries[0]['future_7d_risk'] ?? 65;
        $act1 = $recommendedActions[0]['action'] ?? 'Delay shipments and increase insurance';
        $act2 = $recommendedActions[1]['action'] ?? 'Monitor USD exchange rate every 6 hours';
        $altPort = $altRoutes[0]['alt_port'] ?? 'Singapore Hub';

        return "Current global supply chain conditions indicate an emergency status of [{$emergencyLevel['level']}] due to severe weather volatility and rising regional inflation, particularly affecting {$topRiskName} ({$topRiskScore}% projected risk). " .
               "Recommended executive decision: {$act1}, and {$act2}. " .
               "To preserve profit margins and prevent demurrage penalties, our PHP Rule Engine advises utilizing {$altPort} as the primary alternative transshipment route. " .
               "All expert decisions and financial exposure calculations have been generated automatically by the RiskIntel Hub PHP Rule Engine without external AI dependencies.";
    }

    /**
     * Generate Chart.js datasets for Matrix, Financials, Strategy Comparison, and Doughnut Gauge.
     */
    public function generateChartDatasets(array $matrix, array $financialModel, array $comparison, float $decisionScore): array
    {
        // 1. Scatter Chart for Decision Matrix (Risk vs Impact)
        $scatterData = array_map(function ($row) {
            return [
                'x' => $row['risk_score'],
                'y' => $row['impact_score'],
                'country' => $row['country'],
                'quadrant' => $row['quadrant']
            ];
        }, $matrix);

        // 2. Bar Chart for Financial Impact Breakdown
        $finLabels = array_column($financialModel['breakdown_table'], 'component');
        $finAmounts = array_column($financialModel['breakdown_table'], 'amount');

        // 3. Radar Chart for Strategy Comparison
        $stratLabels = $comparison['chart_data']['labels'];
        $stratCurrent = $comparison['chart_data']['current_strategy'];
        $stratRec = $comparison['chart_data']['recommended_strategy'];

        // 4. Doughnut Gauge for Decision Score
        $remainScore = max(0, 100 - $decisionScore);

        return [
            'matrix_scatter' => [
                'data' => $scatterData
            ],
            'financial_bar' => [
                'labels' => ['Delay Cost', 'Insurance', 'Inventory', 'Revenue Risk', 'Currency Loss'],
                'data' => [
                    $financialModel['delay_cost'],
                    $financialModel['insurance_cost'],
                    $financialModel['inventory_cost'],
                    $financialModel['revenue_risk'],
                    $financialModel['currency_loss']
                ]
            ],
            'strategy_radar' => [
                'labels' => $stratLabels,
                'current_data' => $stratCurrent,
                'recommended_data' => $stratRec
            ],
            'score_gauge' => [
                'score' => $decisionScore,
                'remain' => $remainScore,
                'color' => $decisionScore >= 65 ? 'danger' : ($decisionScore >= 40 ? 'warning' : 'success')
            ]
        ];
    }

    /**
     * Helper to get highest delay days across countries.
     */
    protected function getHighestDelayDays(array $countries): string
    {
        foreach ($countries as $c) {
            if (($c['delay_probability_score'] ?? 0) >= 65) return '7 Days';
        }
        foreach ($countries as $c) {
            if (($c['delay_probability_score'] ?? 0) >= 50) return '5 Days';
        }
        foreach ($countries as $c) {
            if (($c['delay_probability_score'] ?? 0) >= 35) return '3 Days';
        }
        return '1 Day';
    }

    /**
     * Helper to get Priority badge color.
     */
    protected function getPriorityColor(string $priority): string
    {
        switch ($priority) {
            case 'CRITICAL': return 'danger';
            case 'HIGH': return 'warning';
            case 'MEDIUM': return 'info';
            default: return 'success';
        }
    }

    /**
     * Generate structured data for Section 8: Country Comparison Engine (GDP, Inflation, Risk, Weather, Currency).
     */
    public function generateComparisonEngineData(array $countries): array
    {
        $comparisonCountries = [];
        $benchmarks = [
            'DE' => ['flag' => '🇩🇪', 'gdp_val' => '$4.46 Trillion', 'gdp_growth' => '0.9%', 'gdp_num' => 0.9, 'gdp_status' => 'Advanced Industrial Economy', 'inf_rate' => '3.2%', 'inf_status' => 'Moderate Price Pressure', 'cur_code' => 'EUR (€) - $1.08 USD', 'cur_vol' => '12.4 (Low Volatility)', 'weather_cond' => 'Clear Skies & Calm Maritime', 'wind' => '14 knots (Calm)', 'rain' => '12 mm/hr (Normal)'],
            'AU' => ['flag' => '🇦🇺', 'gdp_val' => '$1.69 Trillion', 'gdp_growth' => '2.4%', 'gdp_num' => 2.4, 'gdp_status' => 'Commodity & Resource Hub', 'inf_rate' => '3.8%', 'inf_status' => 'Target Corridor', 'cur_code' => 'AUD ($) - $0.66 USD', 'cur_vol' => '14.8 (Stable)', 'weather_cond' => 'Seasonal Coastal Breezes', 'wind' => '18 knots (Moderate)', 'rain' => '24 mm/hr (Seasonal)'],
            'ID' => ['flag' => '🇮🇩', 'gdp_val' => '$1.37 Trillion', 'gdp_growth' => '5.05%', 'gdp_num' => 5.05, 'gdp_status' => 'Rapid Emerging Growth', 'inf_rate' => '2.8%', 'inf_status' => 'Optimal Price Stability', 'cur_code' => 'IDR (Rp) - $0.000063 USD', 'cur_vol' => '16.2 (Controlled)', 'weather_cond' => 'Monsoon Transit Activity', 'wind' => '22 knots (Breezy)', 'rain' => '38 mm/hr (Heavy)'],
            'CN' => ['flag' => '🇨🇳', 'gdp_val' => '$17.79 Trillion', 'gdp_growth' => '5.2%', 'gdp_num' => 5.2, 'gdp_status' => 'Global Manufacturing Powerhouse', 'inf_rate' => '0.3%', 'inf_status' => 'Deflationary Watch', 'cur_code' => 'CNY (¥) - $0.14 USD', 'cur_vol' => '18.5 (Managed Float)', 'weather_cond' => 'Typhoon Watch Corridor', 'wind' => '28 knots (Strong)', 'rain' => '45 mm/hr (Squall)'],
            'US' => ['flag' => '🇺🇸', 'gdp_val' => '$27.36 Trillion', 'gdp_growth' => '2.5%', 'gdp_num' => 2.5, 'gdp_status' => 'Global Consumer & Financial Hub', 'inf_rate' => '3.4%', 'inf_status' => 'Sticky Service Inflation', 'cur_code' => 'USD ($) - Base Reserve', 'cur_vol' => '10.0 (Benchmark Safe Haven)', 'weather_cond' => 'Regional Atlantic Activity', 'wind' => '16 knots (Calm)', 'rain' => '15 mm/hr (Normal)'],
            'SG' => ['flag' => '🇸🇬', 'gdp_val' => '$501.4 Billion', 'gdp_growth' => '3.2%', 'gdp_num' => 3.2, 'gdp_status' => 'Global Transshipment Center', 'inf_rate' => '2.7%', 'inf_status' => 'Stable Import Pricing', 'cur_code' => 'SGD ($) - $0.74 USD', 'cur_vol' => '11.2 (Highly Stable)', 'weather_cond' => 'Equatorial Clear Waters', 'wind' => '12 knots (Calm)', 'rain' => '18 mm/hr (Showers)'],
            'JP' => ['flag' => '🇯🇵', 'gdp_val' => '$4.21 Trillion', 'gdp_growth' => '1.2%', 'gdp_num' => 1.2, 'gdp_status' => 'Precision Tech Export Economy', 'inf_rate' => '2.8%', 'inf_status' => 'Policy Normalization', 'cur_code' => 'JPY (¥) - $0.0064 USD', 'cur_vol' => '24.1 (Yen Weakness Watch)', 'weather_cond' => 'Seasonal Typhoon Track', 'wind' => '30 knots (High Wind)', 'rain' => '52 mm/hr (Heavy Rain)'],
            'GB' => ['flag' => '🇬🇧', 'gdp_val' => '$3.33 Trillion', 'gdp_growth' => '1.1%', 'gdp_num' => 1.1, 'gdp_status' => 'Services & Financial Trade Hub', 'inf_rate' => '3.9%', 'inf_status' => 'Elevated Core Inflation', 'cur_code' => 'GBP (£) - $1.27 USD', 'cur_vol' => '15.4 (Moderate Volatility)', 'weather_cond' => 'North Atlantic Swells', 'wind' => '20 knots (Breezy)', 'rain' => '22 mm/hr (Drizzle)'],
            'NL' => ['flag' => '🇳🇱', 'gdp_val' => '$1.12 Trillion', 'gdp_growth' => '1.4%', 'gdp_num' => 1.4, 'gdp_status' => 'European Gateway Hub (Rotterdam)', 'inf_rate' => '3.1%', 'inf_status' => 'Moderate Energy Pressure', 'cur_code' => 'EUR (€) - $1.08 USD', 'cur_vol' => '12.4 (Low Volatility)', 'weather_cond' => 'North Sea Coastal Breezes', 'wind' => '18 knots (Moderate)', 'rain' => '16 mm/hr (Normal)'],
            'IN' => ['flag' => '🇮🇳', 'gdp_val' => '$3.75 Trillion', 'gdp_growth' => '6.8%', 'gdp_num' => 6.8, 'gdp_status' => 'High-Growth Industrial Expansion', 'inf_rate' => '4.8%', 'inf_status' => 'Food & Fuel Price Pressure', 'cur_code' => 'INR (₹) - $0.012 USD', 'cur_vol' => '17.8 (Stable Float)', 'weather_cond' => 'Indian Ocean Monsoon', 'wind' => '24 knots (Breezy)', 'rain' => '42 mm/hr (Monsoon)'],
        ];

        foreach ($countries as $c) {
            $iso = strtoupper($c['iso'] ?? 'ID');
            $name = $c['name'] ?? 'Indonesia';
            $bm = $benchmarks[$iso] ?? null;

            $gdpVal = $bm ? $bm['gdp_val'] : '$' . round((abs($c['lat'] ?? 10) + 10) * 15.5, 1) . ' Billion';
            $gdpGrowthNum = $bm ? $bm['gdp_num'] : round(2.0 + ((abs($c['lng'] ?? 100) % 5) * 0.8), 1);
            $gdpGrowth = $bm ? $bm['gdp_growth'] : $gdpGrowthNum . '%';
            $gdpStatus = $bm ? $bm['gdp_status'] : 'Developing Regional Economy';

            $infRate = $bm ? $bm['inf_rate'] : round(1.5 + (($c['inflation_risk'] ?? 30) / 15), 1) . '%';
            $infStatus = $bm ? $bm['inf_status'] : (($c['inflation_risk'] ?? 30) > 40 ? 'Elevated Price Pressure' : 'Stable Price Range');

            $curCode = $bm ? $bm['cur_code'] : $iso . ' ($ / FX Stable)';
            $curVol = $bm ? $bm['cur_vol'] : round(10 + (($c['currency_risk'] ?? 20) / 4), 1) . ' (Index Score)';

            $weatherCond = $bm ? $bm['weather_cond'] : (($c['weather_risk'] ?? 30) > 50 ? 'Active Coastal Weather' : 'Clear & Stable Shipping');
            $wind = $bm ? $bm['wind'] : round(12 + (($c['weather_risk'] ?? 30) * 0.35), 0) . ' knots';
            $rain = $bm ? $bm['rain'] : round(10 + (($c['weather_risk'] ?? 30) * 0.5), 0) . ' mm/hr';

            $comparisonCountries[$iso] = [
                'name' => $name,
                'iso' => $iso,
                'flag' => $bm['flag'] ?? '🌐',
                'gdp' => [
                    'value' => $gdpVal,
                    'growth' => $gdpGrowth,
                    'growth_num' => $gdpGrowthNum,
                    'status' => $gdpStatus,
                    'score' => round(100 - (($c['current_risk'] ?? 30) * 0.5), 1)
                ],
                'inflation' => [
                    'rate' => $infRate,
                    'score' => round($c['inflation_risk'] ?? 30, 1),
                    'status' => $infStatus
                ],
                'risk' => [
                    'score' => round($c['future_7d_risk'] ?? 30, 1),
                    'level' => round($c['future_7d_risk'] ?? 30, 1) > 60 ? 'High Risk' : (round($c['future_7d_risk'] ?? 30, 1) > 35 ? 'Moderate Risk' : 'Low Risk'),
                    'badge_color' => round($c['future_7d_risk'] ?? 30, 1) > 60 ? 'danger' : (round($c['future_7d_risk'] ?? 30, 1) > 35 ? 'warning' : 'success'),
                    'maritime' => round($c['port_risk'] ?? 30, 1),
                    'financial' => round((($c['inflation_risk'] ?? 30) + ($c['currency_risk'] ?? 20)) / 2, 1)
                ],
                'weather' => [
                    'score' => round($c['weather_risk'] ?? 30, 1),
                    'condition' => $weatherCond,
                    'wind_speed' => $wind,
                    'rainfall' => $rain
                ],
                'currency' => [
                    'code' => $curCode,
                    'score' => round($c['currency_risk'] ?? 20, 1),
                    'volatility' => $curVol,
                    'trend' => $c['trend'] ?? 'Stable'
                ]
            ];
        }

        if (!isset($comparisonCountries['DE'])) {
            $bm = $benchmarks['DE'];
            $comparisonCountries['DE'] = [
                'name' => 'Germany',
                'iso' => 'DE',
                'flag' => '🇩🇪',
                'gdp' => ['value' => $bm['gdp_val'], 'growth' => $bm['gdp_growth'], 'growth_num' => $bm['gdp_num'], 'status' => $bm['gdp_status'], 'score' => 88.0],
                'inflation' => ['rate' => $bm['inf_rate'], 'score' => 42.0, 'status' => $bm['inf_status']],
                'risk' => ['score' => 25.0, 'level' => 'Low Risk', 'badge_color' => 'success', 'maritime' => 30.0, 'financial' => 31.0],
                'weather' => ['score' => 25.0, 'condition' => $bm['weather_cond'], 'wind_speed' => $bm['wind'], 'rainfall' => $bm['rain']],
                'currency' => ['code' => $bm['cur_code'], 'score' => 20.0, 'volatility' => $bm['cur_vol'], 'trend' => 'Stable']
            ];
        }
        if (!isset($comparisonCountries['AU'])) {
            $bm = $benchmarks['AU'];
            $comparisonCountries['AU'] = [
                'name' => 'Australia',
                'iso' => 'AU',
                'flag' => '🇦🇺',
                'gdp' => ['value' => $bm['gdp_val'], 'growth' => $bm['gdp_growth'], 'growth_num' => $bm['gdp_num'], 'status' => $bm['gdp_status'], 'score' => 82.0],
                'inflation' => ['rate' => $bm['inf_rate'], 'score' => 28.0, 'status' => $bm['inf_status']],
                'risk' => ['score' => 35.0, 'level' => 'Low-Medium Risk', 'badge_color' => 'info', 'maritime' => 25.0, 'financial' => 25.0],
                'weather' => ['score' => 35.0, 'condition' => $bm['weather_cond'], 'wind_speed' => $bm['wind'], 'rainfall' => $bm['rain']],
                'currency' => ['code' => $bm['cur_code'], 'score' => 22.0, 'volatility' => $bm['cur_vol'], 'trend' => 'Stable']
            ];
        }

        return [
            'default_country_a' => 'DE',
            'default_country_b' => 'AU',
            'countries' => $comparisonCountries
        ];
    }

    /**
     * Helper to get Decision Score badge label.
     */
    protected function getDecisionScoreBadge(float $score): string
    {
        if ($score >= 70) return 'IMMEDIATE ACTION REQUIRED';
        if ($score >= 50) return 'HIGH INTERVENTION PRIORITY';
        if ($score >= 30) return 'MODERATE ADVISORY';
        return 'OPTIMAL PASSIVE MONITORING';
    }

    /**
     * Calculate average of a specific key across array.
     */
    protected function calculateAverage(array $items, string $key): float
    {
        if (empty($items)) return 0.0;
        $sum = array_sum(array_column($items, $key));
        return round($sum / count($items), 1);
    }

    /**
     * Clamp float between 0 and 100.
     */
    protected function clamp(float $val): float
    {
        return round(max(0, min(100, $val)), 1);
    }
}
