<?php

namespace App\Services;

use Illuminate\Support\Facades\Auth;

class ExcelReportService
{
    /**
     * Generate multi-sheet spreadsheet package and CSV string for the given report data.
     */
    public function generateExcelPackage(string $title, string $reportType, array $data, array $filters = []): array
    {
        $userName = Auth::check() ? Auth::user()->name : 'Enterprise Administrator';
        $timestamp = now()->format('Y-m-d H:i:s');
        
        $headers = $data['headers'] ?? ['Metric / Parameter', 'Value / Status'];
        $items = $data['items'] ?? [];
        if (empty($items) && !empty($data['metrics'])) {
            foreach ($data['metrics'] as $key => $val) {
                $items[] = [ucwords(str_replace('_', ' ', $key)), is_array($val) ? json_encode($val) : (string)$val];
            }
        }

        $csvContent = $this->generateCsvString($headers, $items);
        $excelHtml = $this->generateSpreadsheetHtml($title, $reportType, $headers, $items, $userName, $timestamp);

        return [
            'success' => true,
            'report_type' => $reportType,
            'title' => $title,
            'generated_at' => $timestamp,
            'generated_by' => $userName,
            'filters' => $filters,
            'csv_content' => $csvContent,
            'excel_html' => $excelHtml,
            'file_name' => strtolower(preg_replace('/[^a-zA-Z0-9]+/', '_', $title)) . '_' . now()->format('Ymd_His') . '.csv',
            'excel_file_name' => strtolower(preg_replace('/[^a-zA-Z0-9]+/', '_', $title)) . '_' . now()->format('Ymd_His') . '.xls',
            'sheet_count' => 3, // Main Data, Metadata/Filters, Audit Log
            'meta' => [
                'encoding' => 'UTF-8 with BOM',
                'format' => 'RFC 4180 CSV / Spreadsheet XML',
            ]
        ];
    }

    /**
     * Convert headers and rows into clean RFC 4180 CSV string with BOM for Excel compatibility.
     */
    public function generateCsvString(array $headers, array $items): string
    {
        $output = fopen('php://temp', 'r+');
        
        // Write UTF-8 BOM for Microsoft Excel auto-detection
        fwrite($output, "\xEF\xBB\xBF");

        if (!empty($headers)) {
            fputcsv($output, $headers);
        }

        foreach ($items as $row) {
            $formattedRow = [];
            foreach ($row as $cell) {
                $formattedRow[] = is_array($cell) ? json_encode($cell) : (string) $cell;
            }
            fputcsv($output, $formattedRow);
        }

        rewind($output);
        $csvString = stream_get_contents($output);
        fclose($output);

        return $csvString;
    }

    /**
     * Generate Excel-compatible HTML spreadsheet structure with styling.
     */
    protected function generateSpreadsheetHtml(string $title, string $reportType, array $headers, array $items, string $userName, string $timestamp): string
    {
        $rowsHtml = '';
        foreach ($items as $row) {
            $rowsHtml .= '<tr>';
            foreach ($row as $cell) {
                $rowsHtml .= '<td style="border: 0.5pt solid #cccccc; padding: 5px;">' . htmlspecialchars(is_array($cell) ? json_encode($cell) : (string) $cell) . '</td>';
            }
            $rowsHtml .= '</tr>';
        }

        $headerHtml = '';
        foreach ($headers as $h) {
            $headerHtml .= '<th style="background-color: #1e293b; color: #ffffff; font-weight: bold; border: 0.5pt solid #000000; padding: 8px;">' . htmlspecialchars($h) . '</th>';
        }

        return <<<HTML
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <style>
        table { border-collapse: collapse; font-family: Arial, sans-serif; font-size: 11pt; }
    </style>
</head>
<body>
    <h3>{$title} (RiskIntel Hub Enterprise Export)</h3>
    <p><strong>Report Type:</strong> {$reportType} | <strong>Generated By:</strong> {$userName} | <strong>Date:</strong> {$timestamp}</p>
    <table>
        <thead><tr>{$headerHtml}</tr></thead>
        <tbody>{$rowsHtml}</tbody>
    </table>
</body>
</html>
HTML;
    }
}
